using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using PokerFrontend.Infrastructure.Enums;
using PokerFrontend.Infrastructure.Models;

namespace PokerFrontend.Business
{
    public class RangesBusinessHandler
    {
        public PreFlopRange BuildDefaultRanges()
        {
            return
                new PreFlopRange("", 100, 100, 0, 0,
                    new List<PreFlopAction>
                    {
                        new PreFlopAction("UTG Open", "", DecisionKind.Bet,2.5m,"",""),
                        new PreFlopAction("HJ Open", "f", DecisionKind.Bet,2.5m,"",""),
                        new PreFlopAction("CO Open", "ff", DecisionKind.Bet,2.5m,"",""),
                        new PreFlopAction("BTN Open", "fff", DecisionKind.Bet,2.5m,"",""),
                        new PreFlopAction("SB Open", "ffff", DecisionKind.Bet,3,"",""),
                        new PreFlopAction("BB Call vs UTG", "bffff", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BB 3bet vs UTG", "bffff", DecisionKind.Bet,12,"",""),
                        new PreFlopAction("BB Call vs HJ", "fbfff", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BB 3bet vs HJ", "fbfff", DecisionKind.Bet,12,"",""),
                        new PreFlopAction("BB Call vs CO", "ffbff", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BB 3bet vs CO", "ffbff", DecisionKind.Bet,12,"",""),
                        new PreFlopAction("BB Call vs BTN", "fffbf", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BB 3bet vs BTN", "fffbf", DecisionKind.Bet,12,"",""),
                        new PreFlopAction("BB Call vs SB", "ffffb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BB 3bet vs SB", "ffffb", DecisionKind.Bet,10,"",""),
                        new PreFlopAction("SB Call vs UTG", "bfff", DecisionKind.Call,0,"",""),
                        new PreFlopAction("SB 3bet vs UTG", "bfff", DecisionKind.Bet,11,"",""),
                        new PreFlopAction("SB Call vs HJ", "fbff", DecisionKind.Call,0,"",""),
                        new PreFlopAction("SB 3bet vs HJ", "fbff", DecisionKind.Bet,11,"",""),
                        new PreFlopAction("SB Call vs CO", "ffbf", DecisionKind.Call,0,"",""),
                        new PreFlopAction("SB 3bet vs CO", "ffbf", DecisionKind.Bet,11,"",""),
                        new PreFlopAction("SB Call vs BTN", "fffb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("SB 3bet vs BTN", "fffb", DecisionKind.Bet,11,"",""),
                        new PreFlopAction("BTN Call vs UTG", "bff", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BTN 3bet vs UTG", "bff", DecisionKind.Bet,7.5m,"",""),
                        new PreFlopAction("BTN Call vs HJ", "fbf", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BTN 3bet vs HJ", "fbf", DecisionKind.Bet,7.5m,"",""),
                        new PreFlopAction("BTN Call vs CO", "ffb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BTN 3bet vs CO", "ffb", DecisionKind.Bet,7.5m,"",""),
                        new PreFlopAction("CO Call vs UTG", "bf", DecisionKind.Call,0,"",""),
                        new PreFlopAction("CO 3bet vs UTG", "bf", DecisionKind.Bet,7.5m,"",""),
                        new PreFlopAction("CO Call vs HJ", "fb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("CO 3bet vs HJ", "fb", DecisionKind.Bet,7.5m,"",""),
                        new PreFlopAction("HJ Call vs UTG", "b", DecisionKind.Call,0,"",""),
                        new PreFlopAction("HJ 3bet vs UTG", "b", DecisionKind.Bet,7.5m,"",""),
                        new PreFlopAction("UTG Call vs BB3bet", "bffffb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("UTG 4Bet vs BB3bet", "bffffb", DecisionKind.Bet,27,"",""),
                        new PreFlopAction("UTG Call vs SB3bet", "bfffbf", DecisionKind.Call,0,"",""),
                        new PreFlopAction("UTG 4Bet vs SB3bet", "bfffbf", DecisionKind.Bet,25,"",""),
                        new PreFlopAction("UTG Call vs BTN3bet", "bffbff", DecisionKind.Call,0,"",""),
                        new PreFlopAction("UTG 4Bet vs BTN3bet", "bffbff", DecisionKind.Bet,20,"",""),
                        new PreFlopAction("UTG Call vs CO3bet", "bfbfff", DecisionKind.Call,0,"",""),
                        new PreFlopAction("UTG 4Bet vs CO3bet", "bfbfff", DecisionKind.Bet,20,"",""),
                        new PreFlopAction("UTG Call vs HJ3bet", "bbffff", DecisionKind.Call,0,"",""),
                        new PreFlopAction("UTG 4Bet vs HJ3bet", "bbffff", DecisionKind.Bet,20,"",""),
                        new PreFlopAction("HJ Call vs BB3bet", "fbfffb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("HJ 4Bet vs BB3bet", "fbfffb", DecisionKind.Bet,27,"",""),
                        new PreFlopAction("HJ Call vs SB3bet", "fbffbf", DecisionKind.Call,0,"",""),
                        new PreFlopAction("HJ 4Bet vs SB3bet", "fbffbf", DecisionKind.Bet,25,"",""),
                        new PreFlopAction("HJ Call vs BTN3bet", "fbfbff", DecisionKind.Call,0,"",""),
                        new PreFlopAction("HJ 4Bet vs BTN3bet", "fbfbff", DecisionKind.Bet,20,"",""),
                        new PreFlopAction("HJ Call vs CO3bet", "fbbfff", DecisionKind.Call,0,"",""),
                        new PreFlopAction("HJ 4Bet vs CO3bet", "fbbfff", DecisionKind.Bet,20,"",""),
                        new PreFlopAction("CO Call vs BB3bet", "ffbffb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("CO 4Bet vs BB3bet", "ffbffb", DecisionKind.Bet,27,"",""),
                        new PreFlopAction("CO Call vs SB3bet", "ffbfbf", DecisionKind.Call,0,"",""),
                        new PreFlopAction("CO 4Bet vs SB3bet", "ffbfbf", DecisionKind.Bet,25,"",""),
                        new PreFlopAction("CO Call vs BTN3bet", "ffbbff", DecisionKind.Call,0,"",""),
                        new PreFlopAction("CO 4Bet vs BTN3bet", "ffbbff", DecisionKind.Bet,20,"",""),
                        new PreFlopAction("BTN Call vs BB3bet", "fffbfb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BTN 4Bet vs BB3bet", "fffbfb", DecisionKind.Bet,27,"",""),
                        new PreFlopAction("BTN Call vs SB3bet", "fffbbf", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BTN 4Bet vs SB3bet", "fffbbf", DecisionKind.Bet,25,"",""),
                        new PreFlopAction("SB Call vs SB3bet", "ffffbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("SB 4Bet vs SB3bet", "ffffbb", DecisionKind.Bet,25,"",""),
                        new PreFlopAction("BB Call vs UTG4bet", "bffffbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BB Allin vs UTG4bet", "bffffbb", DecisionKind.Bet,-1,"",""),
                        new PreFlopAction("BB Call vs HJ4bet", "fbfffbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BB Allin vs HJ4bet", "fbfffbb", DecisionKind.Bet,-1,"",""),
                        new PreFlopAction("BB Call vs CO4bet", "ffbffbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BB Allin vs CO4bet", "ffbffbb", DecisionKind.Bet,-1,"",""),
                        new PreFlopAction("BB Call vs BTN4bet", "fffbfbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BB Allin vs BTN4bet", "fffbfbb", DecisionKind.Bet,-1,"",""),
                        new PreFlopAction("BB Call vs SB4bet", "ffffbbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BB Allin vs SB4bet", "ffffbbb", DecisionKind.Bet,-1,"",""),
                        new PreFlopAction("SB Call vs UTG4bet", "bfffbfb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("SB Allin vs UTG4bet", "bfffbfb", DecisionKind.Bet,-1,"",""),
                        new PreFlopAction("SB Call vs HJ4bet", "fbffbfb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("SB Allin vs HJ4bet", "fbffbfb", DecisionKind.Bet,-1,"",""),
                        new PreFlopAction("SB Call vs CO4bet", "ffbfbfb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("SB Allin vs CO4bet", "ffbfbfb", DecisionKind.Bet,-1,"",""),
                        new PreFlopAction("SB Call vs BTN4bet", "fffbbfb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("SB Allin vs BTN4bet", "fffbbfb", DecisionKind.Bet,-1,"",""),
                        new PreFlopAction("BTN Call vs UTG4bet", "bffbffb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BTN Allin vs UTG4bet", "bffbffb", DecisionKind.Bet,-1,"",""),
                        new PreFlopAction("BTN Call vs HJ4bet", "fbfbffb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BTN Allin vs HJ4bet", "fbfbffb", DecisionKind.Bet,-1,"",""),
                        new PreFlopAction("BTN Call vs CO4bet", "ffbbffb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BTN Allin vs CO4bet", "ffbbffb", DecisionKind.Bet,-1,"",""),
                        new PreFlopAction("CO Call vs UTG4bet", "bfbfffb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("CO Allin vs UTG4bet", "bfbfffb", DecisionKind.Bet,-1,"",""),
                        new PreFlopAction("CO Call vs HJ4bet", "fbbfffb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("CO Allin vs HJ4bet", "fbbfffb", DecisionKind.Bet,-1,"",""),
                        new PreFlopAction("HJ Call vs UTG4bet", "bbffffb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("HJ Allin vs UTG4bet", "bbffffb", DecisionKind.Bet,-1,"",""),
                        new PreFlopAction("UTG Call BB Allin", "bffffbbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("UTG Call SB Allin", "bfffbfbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("UTG Call BTN Allin", "bffbffbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("UTG Call CO Allin", "bfbfffbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("UTG Call HJ Allin", "bbffffbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("HJ Call BB Allin", "fbfffbbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("HJ Call SB Allin", "fbffbfbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("HJ Call BTN Allin", "fbfbffbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("HJ Call CO Allin", "fbbfffbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("CO Call BB Allin", "ffbffbbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("CO Call SB Allin", "ffbfbfbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("CO Call BTN Allin", "ffbbffbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BTN Call BB Allin", "fffbfbbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("BTN Call SB Allin", "fffbbfbb", DecisionKind.Call,0,"",""),
                        new PreFlopAction("SB Call BB Allin", "ffffbbbb", DecisionKind.Call,0,"",""),

                    });

        }
    }
}
